apiVersion: v1
kind: ReplicationController
metadata:
  name: iginx-rc
spec:
  replicas: 5
  selector:
    app: nginx-1
  template:
    metadata:
      name: myapp
      labels:
        app: nginx-1
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80
